// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloUtilities = require("apollo-utilities");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var authLink = ApolloLinks.createContextLink((function (param) {
        return {
                headers: {
                  "x-hasura-admin-secret": "myadminsecretkey"
                }
              };
      }));

var httpLink = ApolloLinks.createHttpLink("http://localhost:8080/v1alpha1/graphql", undefined, undefined, undefined, "include", undefined, /* () */0);

var webSocketLink = ApolloLinks.webSocketLink("ws://localhost:8080/v1alpha1/graphql", true, /* () */0);

var webSocketHttpLink = ApolloLink.split((function (operation) {
        var operationDefition = ApolloUtilities.getMainDefinition(operation.query);
        if (operationDefition.kind === "OperationDefinition") {
          return operationDefition.operation === "subscription";
        } else {
          return false;
        }
      }), webSocketLink, httpLink);

var instance = ReasonApollo.createApolloClient(ApolloLink.from(/* array */[
          authLink,
          webSocketHttpLink
        ]), inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

exports.inMemoryCache = inMemoryCache;
exports.authLink = authLink;
exports.httpLink = httpLink;
exports.webSocketLink = webSocketLink;
exports.webSocketHttpLink = webSocketHttpLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
