// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var Questions$ReactTemplate = require("./Questions.bs.js");
var QuestionForm$ReactTemplate = require("./QuestionForm.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[React.createElement("div", undefined, ReasonReact.element(undefined, undefined, QuestionForm$ReactTemplate.make(/* array */[])), ReasonReact.element(undefined, undefined, Questions$ReactTemplate.make(/* array */[])))])), "index2");

/*  Not a pure module */
