// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");

function ste(prim) {
  return prim;
}

var ppx_printed_query = "mutation askQuestion($body: String!)  {\ninsert_question(objects: {body: $body})  {\nreturning  {\nbody  \ncreated_at  \nid  \nupdated_at  \nvotes_aggregate  {\naggregate  {\ncount(columns: user_id, distinct: true)  \n}\n\n}\n\n}\n\n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "insert_question");
    var tmp;
    if (match$1 !== undefined) {
      var value$1 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeNull(value$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(value$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var match$4 = Js_dict.get(Caml_option.valFromOption(match$3), "returning");
          var tmp$2;
          if (match$4 !== undefined) {
            var value$2 = Caml_option.valFromOption(match$4);
            var match$5 = Js_json.decodeArray(value$2);
            tmp$2 = match$5 !== undefined ? match$5.map((function (value) {
                      var match = Js_json.decodeObject(value);
                      if (match !== undefined) {
                        var value$1 = Caml_option.valFromOption(match);
                        var match$1 = Js_dict.get(value$1, "body");
                        var tmp;
                        if (match$1 !== undefined) {
                          var value$2 = Caml_option.valFromOption(match$1);
                          var match$2 = Js_json.decodeString(value$2);
                          tmp = match$2 !== undefined ? match$2 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$2));
                        } else {
                          tmp = Js_exn.raiseError("graphql_ppx: Field body on type question is missing");
                        }
                        var match$3 = Js_dict.get(value$1, "created_at");
                        var match$4 = Js_dict.get(value$1, "id");
                        var match$5 = Js_dict.get(value$1, "updated_at");
                        var match$6 = Js_dict.get(value$1, "votes_aggregate");
                        var tmp$1;
                        if (match$6 !== undefined) {
                          var match$7 = Js_json.decodeObject(Caml_option.valFromOption(match$6));
                          if (match$7 !== undefined) {
                            var match$8 = Js_dict.get(Caml_option.valFromOption(match$7), "aggregate");
                            var tmp$2;
                            if (match$8 !== undefined) {
                              var value$3 = Caml_option.valFromOption(match$8);
                              var match$9 = Js_json.decodeNull(value$3);
                              if (match$9 !== undefined) {
                                tmp$2 = undefined;
                              } else {
                                var match$10 = Js_json.decodeObject(value$3);
                                var tmp$3;
                                if (match$10 !== undefined) {
                                  var match$11 = Js_dict.get(Caml_option.valFromOption(match$10), "count");
                                  var tmp$4;
                                  if (match$11 !== undefined) {
                                    var value$4 = Caml_option.valFromOption(match$11);
                                    var match$12 = Js_json.decodeNull(value$4);
                                    if (match$12 !== undefined) {
                                      tmp$4 = undefined;
                                    } else {
                                      var match$13 = Js_json.decodeNumber(value$4);
                                      tmp$4 = match$13 !== undefined ? match$13 | 0 : Js_exn.raiseError("graphql_ppx: Expected int, got " + JSON.stringify(value$4));
                                    }
                                  } else {
                                    tmp$4 = undefined;
                                  }
                                  tmp$3 = {
                                    count: tmp$4
                                  };
                                } else {
                                  tmp$3 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                }
                                tmp$2 = Caml_option.some(tmp$3);
                              }
                            } else {
                              tmp$2 = undefined;
                            }
                            tmp$1 = {
                              aggregate: tmp$2
                            };
                          } else {
                            tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                          }
                        } else {
                          tmp$1 = Js_exn.raiseError("graphql_ppx: Field votes_aggregate on type question is missing");
                        }
                        return {
                                body: tmp,
                                created_at: match$3 !== undefined ? Caml_option.valFromOption(match$3) : Js_exn.raiseError("graphql_ppx: Field created_at on type question is missing"),
                                id: match$4 !== undefined ? Caml_option.valFromOption(match$4) : Js_exn.raiseError("graphql_ppx: Field id on type question is missing"),
                                updated_at: match$5 !== undefined ? Caml_option.valFromOption(match$5) : Js_exn.raiseError("graphql_ppx: Field updated_at on type question is missing"),
                                votes_aggregate: tmp$1
                              };
                      } else {
                        return Js_exn.raiseError("graphql_ppx: Object is not a value");
                      }
                    })) : Js_exn.raiseError("graphql_ppx: Expected array, got " + JSON.stringify(value$2));
          } else {
            tmp$2 = Js_exn.raiseError("graphql_ppx: Field returning on type question_mutation_response is missing");
          }
          tmp$1 = {
            returning: tmp$2
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Caml_option.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            insert_question: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(body, param) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[/* tuple */[
                  "body",
                  body
                ]]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var body = variables.body;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[/* tuple */[
                  "body",
                  body
                ]]),
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var AskQuestion = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var AskQuestionMutation = ReasonApollo.CreateMutation([
      ppx_printed_query,
      parse
    ]);

var component = ReasonReact.reducerComponent("QuestionForm");

function make$1(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Curry._4(AskQuestionMutation[/* make */5], undefined, undefined, undefined, (function (mutation, _result) {
                                return React.createElement("div", undefined, React.createElement("h1", undefined, "Your Question"), React.createElement("h2", undefined, self[/* state */1][/* text */0]), React.createElement("textarea", {
                                                value: self[/* state */1][/* text */0],
                                                onChange: (function ($$event) {
                                                    var value = $$event.target.value;
                                                    return Curry._1(self[/* send */3], /* UpdateFormValue */[value]);
                                                  })
                                              }), React.createElement("br", undefined), React.createElement("button", {
                                                onClick: (function (_mouseEvent) {
                                                    var askNewQuestion = make(self[/* state */1][/* text */0], /* () */0);
                                                    Curry._4(mutation, Caml_option.some(askNewQuestion.variables), /* array */["listQuestions"], undefined, /* () */0);
                                                    return Curry._1(self[/* send */3], /* Clear */0);
                                                  })
                                              }, "Ask away!"));
                              })));
            }),
          /* initialState */(function (param) {
              return /* record */[/* text */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* text */action[0]]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* text */""]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.ste = ste;
exports.AskQuestion = AskQuestion;
exports.AskQuestionMutation = AskQuestionMutation;
exports.component = component;
exports.make = make$1;
/* AskQuestionMutation Not a pure module */
