version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha42
    ports:
    - "8080:8080"
    restart: always
    environment:
      ## See https://docs.hasura.io/1.0/graphql/manual/deployment/docker/index.html for docker network config 
      HASURA_GRAPHQL_DATABASE_URL: postgres://host.docker.internal:5432/cc_local?user=postgres&password=&sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      ##HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
